#
# Old conda-forge PR for the CPU version:
#   https://github.com/conda-forge/staged-recipes/pull/1416
#

# N.B. revisit makefile and (vis-/gpu-)requirements.txt when updating the recipe
# In particular, we are "unpinning" (making >= instead of ==) their dependencies.
{% extends "base.yaml" %}

{% block recipe %}

package:
  name: neon
  version: {{ neon_version }}

source:
  fn: neon-v{{ neon_version }}.tar.gz
  url: https://github.com/NervanaSystems/neon/archive/v{{ neon_version }}.tar.gz
  sha256: a6f8d64139f4917002ac5d7a4378136f4a4c5040b82e81bec4e83465c0b4bb4a
  patches:
    # More generic perl shebang; fix using deprecated numpy API (breaks already in 1.12)
    - fix-perl-shebang-deprecated-np.patch

build:
  number: 0
  skip: true  # [not linux]
  script:
    - HAS_GPU=0 VIS=1 make sysinstall_nodeps

  features:
    - blas_{{ blas_variant }}

requirements:
  # From (vis-)(gpu-)requirements.txt (would need to unpin dependencies)
  # N.B. revisit makefiles and (vis-/gpu-)requirements.txt when updating the recipe

  build:
    - pkg-config
    - cython  # N.B. look at Makefile

    - python
    - numpy x.x
    - blas 1.1 {{ blas_variant }}
    - openblas 0.2.19|0.2.19.*
    - hdf5 1.8.17|1.8.17.*
    - pyyaml >=3.12

    # Really needed?
    - aeon

    # We are not generating any doc...
    # - sphinx >=1.4.6

    - configargparse >=0.10.0
    - appdirs >=1.4.0
    - posix_ipc >=1.0.0
    - pillow >=3.3.1
    - h5py >=2.6.0
    - future >=0.15.2
    - tqdm >=4.8.4
    - bokeh >=0.9.3
    - jinja2 >=2.8
    - pytools

  run:
    - python
    - numpy x.x
    - blas 1.1 {{ blas_variant }}
    - openblas 0.2.19|0.2.19.*

    - aeon

    - configargparse >=0.10.0
    - appdirs >=1.4.0
    - posix_ipc >=1.0.0
    - pillow >=3.3.1
    - h5py >=2.6.0
    - future >=0.15.2
    - tqdm >=4.8.4
    - bokeh >=0.9.3
    - jinja2 >=2.8
    - pytools

test:
  source_files:
    - tests
  requires:
    # Yes, perl, for maxas...
    #   https://github.com/NervanaSystems/neon/blob/485033cd5e703e70befd82ca8234c97cdf61ab39/neon/backends/kernels/maxas/maxas.pl
    - perl-feature
    - perl
    # Test & lint
    - pep8 >=1.7.0
    - flake8 >=3.0.4
    - pytest >=3.0.1
    - pytest-cov >=2.3.1
    - pylint >=1.6.4
  imports:
    - neon
  commands:
    - neon -h
    - nvis -h
    - py.test -k cpu -m "not hasgpu" tests

about:
  home: https://github.com/NervanaSystems/neon
  license: Apache 2
  license_file: LICENSE
  summary: Intel Nervana reference deep learning framework committed to best performance on all hardware http://neon.nervanasys.com/docs/latest

{% endblock %}
