{% extends 'base.yaml' %}

{% block recipe %}

package:
  name: neon-cuda
  version: {{ neon_cuda_version }}

build:
  number: 0
  track_features:
    - neon_cuda{{ cuda_version }}
  features:
    - cuda{{ cuda_version }}
    - cuda{{ cuda_version }}dev

requirements:
  run:
    - neon

test:
  requires:
    - cuda-feature {{ cuda_version }}
    - cuda-dev-feature {{ cuda_version }}
  imports:
    - neon

{% endblock %}
